title: Scratch 2 op de Raspberry Pi openen
hero_image: images/banner.png
description: Hoe open je Scratch 2.0 op de Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Scratch 2 openen
