title: Opening Scratch 2 on the Raspberry Pi
hero_image: images/banner.png
description: How to open Scratch 2.0 on the Raspberry Pi
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Opening Scratch 2
