title: rpi-scratch2-opening
hero_image: images/banner.png
description: rpi-scratch2-opening description
version: 4
listed: false
copyedit: false
last_tested: "2019-09-11"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
